//ls  node_modules/@mui/material | xargs|  sed "s/ /','/g"
// Then fix it up
const muiKeys = [
  "Accordion",
  "AccordionActions",
  "AccordionDetails",
  "AccordionSummary",
  "Alert",
  "AlertTitle",
  "AppBar",
  "Autocomplete",
  "Avatar",
  "AvatarGroup",
  "Backdrop",
  "Badge",
  "BottomNavigation",
  "BottomNavigationAction",
  "Box",
  "Breadcrumbs",
  "Button",
  "ButtonBase",
  "ButtonGroup",
  "Card",
  "CardActionArea",
  "CardActions",
  "CardContent",
  "CardHeader",
  "CardMedia",
  "Checkbox",
  "Chip",
  "CircularProgress",
  "ClickAwayListener",
  "Collapse",
  "Container",
  "CssBaseline",
  "DefaultPropsProvider",
  "Dialog",
  "DialogActions",
  "DialogContent",
  "DialogContentText",
  "DialogTitle",
  "Divider",
  "Drawer",
  "Fab",
  "Fade",
  "FilledInput",
  "FormControl",
  "FormControlLabel",
  "FormGroup",
  "FormHelperText",
  "FormLabel",
  "GlobalStyles",
  "Grid",
  "Grid2",
  "Grow",
  "Hidden",
  "Icon",
  "IconButton",
  "ImageList",
  "ImageListItem",
  "ImageListItemBar",
  "InitColorSchemeScript",
  "Input",
  "InputAdornment",
  "InputBase",
  "InputLabel",
  "LinearProgress",
  "Link",
  "List",
  "ListItem",
  "ListItemAvatar",
  "ListItemButton",
  "ListItemIcon",
  "ListItemSecondaryAction",
  "ListItemText",
  "ListSubheader",
  "Menu",
  "MenuItem",
  "MenuList",
  "MobileStepper",
  "Modal",
  "NativeSelect",
  "NoSsr",
  "OutlinedInput",
  "Pagination",
  "PaginationItem",
  "Paper",
  "Popover",
  "Popper",
  "Portal",
  "Radio",
  "RadioGroup",
  "Rating",
  "ScopedCssBaseline",
  "Select",
  "Skeleton",
  "Slide",
  "Slider",
  "Snackbar",
  "SnackbarContent",
  "SpeedDial",
  "SpeedDialAction",
  "SpeedDialIcon",
  "Stack",
  "Step",
  "StepButton",
  "StepConnector",
  "StepContent",
  "StepIcon",
  "StepLabel",
  "Stepper",
  "StyledEngineProvider",
  "SvgIcon",
  "SwipeableDrawer",
  "Switch",
  "Tab",
  "TabScrollButton",
  "Table",
  "TableBody",
  "TableCell",
  "TableContainer",
  "TableFooter",
  "TableHead",
  "TablePagination",
  "TableRow",
  "TableSortLabel",
  "Tabs",
  "TextField",
  "TextareaAutosize",
  "ToggleButton",
  "ToggleButtonGroup",
  "Toolbar",
  "Tooltip",
  "Typography",
  "Zoom",
].slice(0, 10);

export function addRandomMuiImport() {
//   const elementName = muiKeys[Math.floor(Math.random() * muiKeys.length)];

    const elementName ="Button";

  console.log(elementName)


//   return {
//     importStatement: '', 
//     importBetter: '', 
//     usage: '', 
//     element: '',
//   }

  return {
    importStatement: `import {${elementName}} from "@mui/material";`,
    importBetter: `import ${elementName} from "@mui/material/${elementName}";`,
    usage: `<${elementName}/>`,
    element: elementName,
  };
}
